package uk.ac.soton.comp1206.event;

import uk.ac.soton.comp1206.game.GamePiece;

/**
 * NextPieceListener is used to listen for the next pieces generated by Game for UI manipulation.
 */
public interface NextPieceListener {

    /**
     * Handle the next piece given by Game.
     * @param nextPiece next piece in Game.
     */
    void nextPiece(GamePiece nextPiece);
}
